[2020-12-23 12:06:09,869] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-12-23 12:16:09,868] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-12-23 12:26:09,868] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-12-23 12:31:13,250] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group O1-Filter0 in Empty state. Created a new member id kafka-python-2.0.2-0cd2bf1d-97c5-4199-a1d6-7f2a33368447 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:31:13,251] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Filter0 in state PreparingRebalance with old generation 5 (__consumer_offsets-21) (reason: Adding new member kafka-python-2.0.2-0cd2bf1d-97c5-4199-a1d6-7f2a33368447 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:31:13,253] INFO [GroupCoordinator 0]: Stabilized group O1-Filter0 generation 6 (__consumer_offsets-21) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:31:13,266] INFO [GroupCoordinator 0]: Assignment received from leader for group O1-Filter0 for generation 6 (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:32:08,655] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-0cd2bf1d-97c5-4199-a1d6-7f2a33368447 in group O1-Filter0 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:32:08,655] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Filter0 in state PreparingRebalance with old generation 6 (__consumer_offsets-21) (reason: removing member kafka-python-2.0.2-0cd2bf1d-97c5-4199-a1d6-7f2a33368447 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:32:08,656] INFO [GroupCoordinator 0]: Group O1-Filter0 with generation 7 is now empty (__consumer_offsets-21) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:17,345] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group O1-Fall_detection0 in Empty state. Created a new member id kafka-python-2.0.2-c5e85249-386e-4f08-8b4f-31f177558872 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:17,346] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Fall_detection0 in state PreparingRebalance with old generation 3 (__consumer_offsets-24) (reason: Adding new member kafka-python-2.0.2-c5e85249-386e-4f08-8b4f-31f177558872 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:17,346] INFO [GroupCoordinator 0]: Stabilized group O1-Fall_detection0 generation 4 (__consumer_offsets-24) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:17,378] INFO [GroupCoordinator 0]: Assignment received from leader for group O1-Fall_detection0 for generation 4 (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:29,375] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group O1-Fall_detection0 in Stable state. Created a new member id kafka-python-2.0.2-536050be-8d4b-4054-bb37-a3dfc4c5ad01 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:29,376] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Fall_detection0 in state PreparingRebalance with old generation 4 (__consumer_offsets-24) (reason: Adding new member kafka-python-2.0.2-536050be-8d4b-4054-bb37-a3dfc4c5ad01 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:36,618] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-c5e85249-386e-4f08-8b4f-31f177558872 in group O1-Fall_detection0 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:36,619] INFO [GroupCoordinator 0]: Stabilized group O1-Fall_detection0 generation 5 (__consumer_offsets-24) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:36,647] INFO [GroupCoordinator 0]: Assignment received from leader for group O1-Fall_detection0 for generation 5 (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:44,283] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group O1-Fall_detection0 in Stable state. Created a new member id kafka-python-2.0.2-e74f21ec-59d0-49c1-8673-f3aa08d92baf for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:44,283] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Fall_detection0 in state PreparingRebalance with old generation 5 (__consumer_offsets-24) (reason: Adding new member kafka-python-2.0.2-e74f21ec-59d0-49c1-8673-f3aa08d92baf with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:51,680] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-536050be-8d4b-4054-bb37-a3dfc4c5ad01 in group O1-Fall_detection0 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:33:51,680] INFO [GroupCoordinator 0]: Stabilized group O1-Fall_detection0 generation 6 (__consumer_offsets-24) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:34:01,680] INFO [GroupCoordinator 0]: Member kafka-python-2.0.2-e74f21ec-59d0-49c1-8673-f3aa08d92baf in group O1-Fall_detection0 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:34:01,681] INFO [GroupCoordinator 0]: Preparing to rebalance group O1-Fall_detection0 in state PreparingRebalance with old generation 6 (__consumer_offsets-24) (reason: removing member kafka-python-2.0.2-e74f21ec-59d0-49c1-8673-f3aa08d92baf on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:34:01,681] INFO [GroupCoordinator 0]: Group O1-Fall_detection0 with generation 7 is now empty (__consumer_offsets-24) (kafka.coordinator.group.GroupCoordinator)
[2020-12-23 12:36:09,869] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-12-23 12:42:36,994] INFO Unable to read additional data from server sessionid 0x100002389910000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:38,297] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:38,351] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:38,822] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-12-23 12:42:38,827] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-12-23 12:42:38,831] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2020-12-23 12:42:39,968] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:39,969] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:40,076] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-12-23 12:42:41,463] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:41,465] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:43,063] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:43,064] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:44,229] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:44,231] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:45,491] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:45,492] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:46,938] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:46,938] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:48,452] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:48,453] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:49,620] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:49,621] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:50,834] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:50,835] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:51,938] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:51,939] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:53,972] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:53,972] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:56,040] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:56,041] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:57,386] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:57,387] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:59,380] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:42:59,381] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:01,378] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:01,379] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:02,538] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-12-23 12:43:02,891] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:02,892] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:04,257] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:04,259] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:05,863] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:05,864] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:07,447] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-12-23 12:43:07,448] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
